# name: Build and Deploy to Github Pages

# on:
#   push:
#     branches:
#       - main  # Here source code branch is `master`, it could be other branch
#   workflow_dispatch:

# jobs:
#   build_and_deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4

#       # Use GitHub Actions' cache to cache dependencies on servers
#       - uses: actions/cache@v4
#         with:
#           path: vendor/bundle
#           key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
#           restore-keys: |
#             ${{ runner.os }}-gems-
#       # Use GitHub Deploy Action to build and deploy to Github
#       - uses: jeffreytse/jekyll-deploy-action@v0.6.0
#         with:
#           provider: 'github'
#           token: ${{ secrets.GITHUB_TOKEN }} # It's your Personal Access Token(PAT)
#           repository: ''             # Default is current repository
#           branch: 'gh-pages'         # Default is gh-pages for github provider
#           jekyll_src: './'           # Default is root directory
#           jekyll_cfg: '_config.yml'  # Default is _config.yml
#           jekyll_baseurl: ''         # Default is according to _config.yml
#           bundler_ver: ''            # Default is compatible bundler ver
#           cname: ''                  # Default is to not use a cname
#           actor: ''                  # Default is the GITHUB_ACTOR
#           pre_build_commands: ''     # Installing additional dependencies (Arch Linux)

name: Deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main  # Change this if your default branch is different

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7' # Match GitHub Pages environment
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Build site with Jekyll
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          repository: ''             # Default is current repository
          branch: 'gh-pages'         # Default is gh-pages for github provider
          jekyll_src: './'           # Default is root directory
          jekyll_cfg: '_config.yml'  # Default is _config.yml
          jekyll_baseurl: ''         # Default is according to _config.yml
          bundler_ver: ''            # Default is compatible bundler ver
          cname: ''                  # Default is to not use a cname
          actor: ''                  # Default is the GITHUB_ACTOR
          pre_build_commands: ''     # Installing additional dependencies (Arch Linux)